# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: pokedex
  host: localhost
  pool: 5
  username: pokedex
  password: pokedex

development:
  adapter: postgresql
  encoding: unicode
  database: pokedex_development
  host: localhost
  pool: 5
  username: pokedex
  password: pokedex

test:
  adapter: postgresql
  encoding: unicode
  database: Pokedex_test
  host: localhost
  pool: 5
  username: pokedex
  password: pokedex
